/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BuyerNetworkRouteImport } from './routes/buyer-network'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SellRouteImport } from './routes/sell'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as BusinessesBusinessIdRouteImport } from './routes/businesses.$businessId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerNetworkRoute = BuyerNetworkRouteImport.update({
  id: '/buyer-network',
  path: '/buyer-network',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesBusinessIdRoute = BusinessesBusinessIdRouteImport.update({
  id: '/businesses/$businessId',
  path: '/businesses/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy': typeof BuyRoute
  '/buyer-network': typeof BuyerNetworkRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/businesses/': typeof BusinessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy': typeof BuyRoute
  '/buyer-network': typeof BuyerNetworkRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/businesses': typeof BusinessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy': typeof BuyRoute
  '/buyer-network': typeof BuyerNetworkRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/businesses/': typeof BusinessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/buy'
    | '/buyer-network'
    | '/contact'
    | '/privacy'
    | '/sell'
    | '/terms'
    | '/businesses/$businessId'
    | '/businesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buy'
    | '/buyer-network'
    | '/contact'
    | '/privacy'
    | '/sell'
    | '/terms'
    | '/businesses/$businessId'
    | '/businesses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/buy'
    | '/buyer-network'
    | '/contact'
    | '/privacy'
    | '/sell'
    | '/terms'
    | '/businesses/$businessId'
    | '/businesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuyRoute: typeof BuyRoute
  BuyerNetworkRoute: typeof BuyerNetworkRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SellRoute: typeof SellRoute
  TermsRoute: typeof TermsRoute
  BusinessesBusinessIdRoute: typeof BusinessesBusinessIdRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-network': {
      id: '/buyer-network'
      path: '/buyer-network'
      fullPath: '/buyer-network'
      preLoaderRoute: typeof BuyerNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$businessId': {
      id: '/businesses/$businessId'
      path: '/businesses/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof BusinessesBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuyRoute: BuyRoute,
  BuyerNetworkRoute: BuyerNetworkRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SellRoute: SellRoute,
  TermsRoute: TermsRoute,
  BusinessesBusinessIdRoute: BusinessesBusinessIdRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
